import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'flowbite/dist/flowbite.css';
import "../globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import { AuthProvider } from "@/contexts/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HTR Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>
      <div className="min-h-screen bg-white dark:bg-gray-900">
        <Header />
        <main className="w-full pt-12">{children}</main>
        <Footer />
      </div>
    </AuthProvider>
    
  );
}
